<?php

return [
    'locales' => [
        'nl-nl' => ['label' => 'Nederlands', 'short' => 'NL'],
        'en-us' => ['label' => 'English (US)', 'short' => 'EN'],
        'en-gb' => ['label' => 'English (UK)', 'short' => 'EN-GB'],
        'de-de' => ['label' => 'Deutsch', 'short' => 'DE'],
        'fr-fr' => ['label' => 'Francais', 'short' => 'FR'],
        'es-es' => ['label' => 'Espanol', 'short' => 'ES'],
        'it-it' => ['label' => 'Italiano', 'short' => 'IT'],
        'pt-pt' => ['label' => 'Portugues (PT)', 'short' => 'PT'],
        'pt-br' => ['label' => 'Portugues (BR)', 'short' => 'BR'],
        'pl-pl' => ['label' => 'Polski', 'short' => 'PL'],
        'da-dk' => ['label' => 'Dansk', 'short' => 'DA'],
        'nn-no' => ['label' => 'Norsk', 'short' => 'NO'],
        'sv-se' => ['label' => 'Svenska', 'short' => 'SV'],
        'fi-fi' => ['label' => 'Suomi', 'short' => 'FI'],
        'el-gr' => ['label' => 'Ellinika', 'short' => 'EL'],
        'hr-hr' => ['label' => 'Hrvatski', 'short' => 'HR'],
        'sr-rs' => ['label' => 'Srpski', 'short' => 'SR'],
        'ca-es' => ['label' => 'Catala', 'short' => 'CA'],
    ],
    'language_defaults' => [
        'nl' => 'nl-nl',
        'en' => 'en-us',
        'de' => 'de-de',
        'fr' => 'fr-fr',
        'es' => 'es-es',
        'it' => 'it-it',
        'pt' => 'pt-pt',
        'pl' => 'pl-pl',
        'da' => 'da-dk',
        'nn' => 'nn-no',
        'no' => 'nn-no',
        'nb' => 'nn-no',
        'sv' => 'sv-se',
        'fi' => 'fi-fi',
        'el' => 'el-gr',
        'hr' => 'hr-hr',
        'sr' => 'sr-rs',
        'ca' => 'ca-es',
    ],
    'units' => [
        'metric' => ['label' => 'Metric', 'short' => 'C'],
        'imperial' => ['label' => 'Imperial', 'short' => 'F'],
        'uk' => ['label' => 'UK', 'short' => 'UK'],
        'scandinavia' => ['label' => 'Scandinavia', 'short' => 'm/s'],
    ],
    'unit_aliases' => [
        'us' => 'imperial',
        'imperial' => 'imperial',
        'metric' => 'metric',
        'uk' => 'uk',
        'scandinavia' => 'scandinavia',
    ],
    'cookies' => [
        'lang' => 'mu_lang',
        'units' => 'mu_units',
        'days' => 90,
    ],
    'accept_language' => [
        'enabled' => true,
        'units_by_region' => [
            'US' => 'imperial',
            'LR' => 'imperial',
            'MM' => 'imperial',
            'GB' => 'uk',
        ],
    ],
];
